name: 'homebot_monitoring'
version: '1.0.0'
config-version: 2

profile: 'homebot_profile'

model-paths: ["homebot/models"]
seed-paths: ["homebot/seeds"]
test-paths: ["homebot/tests"]
target-path: "target"

models:
  homebot_monitoring:
    +materialized: table