apiVersion: 1

datasources:
  # --- Tempo (Tracing) ---
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    editable: true
    uid: tempo
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true

  # --- Loki (Logging) ---
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      # Maximum lines to return
      maxLines: 1000
      # Link logs to traces!
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"  # Regex to find TraceID in log line
          name: TraceID
          url: "$${__value.raw}"          # Link directly to the trace
          urlDisplayLabel: "View Trace"
