server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m


storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-bucket
      endpoint: minio:9000
      access_key: tempo_user
      secret_key: tempo_password
      insecure: true
    wal:
      path: /tmp/tempo/wal
