apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebot
  template:
    metadata:
      labels:
        app: homebot
    spec:
      nodeSelector:
        kubernetes.io/hostname: gluck2 # nuc
      containers:
      - name: homebot
        image: akhaladze/iot-homebot:latest
        imagePullPolicy: Always
        env:
        - name: TELEGRAM_TOKEN
          value: "$(TG_BOT_TOKEN)"
        volumeMounts:
        - name: storage
          mountPath: /app/data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: homebot-pvc
  